version: '3.7'

services:
        dyno-app:
                container_name: dyno-app
                build:
                        context: .
                        dockerfile: Dockerfile
                volumes:
                        - '.:/dyno-app'
                        - '/dyno-app/node_modules'
                        - '/home/divya/.gitconfig:/dyno-app/.gitconfig'
                        - './.git:/dyno-app/.git'
                ports:
                        - 3001:3000
